"""Borsa Istanbul spot-equity signal domain enumerations.

This package intentionally has no dependency on SQLAlchemy, Telegram, pandas or a
market-data provider.  Persistence adapters may store the enum ``value`` fields,
but the domain rules remain usable by live monitoring and point-in-time tests.
"""

from __future__ import annotations

from enum import StrEnum


class SignalStatus(StrEnum):
    PENDING_ENTRY = "PENDING_ENTRY"
    ACTIVE = "ACTIVE"
    TP1_HIT = "TP1_HIT"
    TP2_HIT = "TP2_HIT"
    TP3_HIT = "TP3_HIT"
    STOPPED = "STOPPED"
    EXPIRED = "EXPIRED"
    INVALIDATED = "INVALIDATED"
    CANCELLED = "CANCELLED"
    CLOSED_MANUALLY = "CLOSED_MANUALLY"
    EXIT_PENDING = "EXIT_PENDING"
    UNFILLED = "UNFILLED"
    SUSPENDED = "SUSPENDED"
    CORPORATE_ACTION_ADJUSTED = "CORPORATE_ACTION_ADJUSTED"


class SignalEventType(StrEnum):
    SIGNAL_CREATED = "SIGNAL_CREATED"
    ENTRY_REACHED = "ENTRY_REACHED"
    ENTRY_PARTIALLY_FILLED = "ENTRY_PARTIALLY_FILLED"
    ENTRY_FILLED = "ENTRY_FILLED"
    ENTRY_INVALIDATED = "ENTRY_INVALIDATED"
    ORDER_REMAINED_UNFILLED = "ORDER_REMAINED_UNFILLED"
    SIGNAL_EXPIRED = "SIGNAL_EXPIRED"
    SIGNAL_CANCELLED = "SIGNAL_CANCELLED"
    TP1_REACHED = "TP1_REACHED"
    TP2_REACHED = "TP2_REACHED"
    TP3_REACHED = "TP3_REACHED"
    STOP_REACHED = "STOP_REACHED"
    STOP_EXECUTION_DELAYED = "STOP_EXECUTION_DELAYED"
    STOP_EXECUTED = "STOP_EXECUTED"
    STOP_MOVED = "STOP_MOVED"
    POSITION_CLOSED_MANUALLY = "POSITION_CLOSED_MANUALLY"
    EXIT_PENDING = "EXIT_PENDING"
    CIRCUIT_BREAKER_STARTED = "CIRCUIT_BREAKER_STARTED"
    CIRCUIT_BREAKER_ENDED = "CIRCUIT_BREAKER_ENDED"
    TRADING_SUSPENDED = "TRADING_SUSPENDED"
    TRADING_RESUMED = "TRADING_RESUMED"
    SINGLE_PRICE_SESSION = "SINGLE_PRICE_SESSION"
    CORPORATE_ACTION_APPLIED = "CORPORATE_ACTION_APPLIED"


class EntryOrderType(StrEnum):
    LIMIT_BUY = "LIMIT_BUY"
    BREAKOUT_BUY = "BREAKOUT_BUY"
    NEXT_OPEN = "NEXT_OPEN"
    ENTRY_ZONE = "ENTRY_ZONE"
    MANUAL_ENTRY = "MANUAL_ENTRY"


class BreakoutConfirmationMode(StrEnum):
    PRICE_TOUCH = "price_touch"
    INTRADAY_CROSS = "intraday_cross"
    COMPLETED_CLOSE = "completed_close"
    COMPLETED_CLOSE_VOLUME = "completed_close_volume"
    BREAKOUT_RETEST = "breakout_retest"
    NEXT_CANDLE_OPEN = "next_candle_open"


class FillStatus(StrEnum):
    PENDING = "PENDING"
    FILLED = "FILLED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    UNFILLED = "UNFILLED"
    UNFILLED_LIMIT_LOCK = "UNFILLED_LIMIT_LOCK"
    EXIT_PENDING_LIMIT_LOCK = "EXIT_PENDING_LIMIT_LOCK"
    FILLED_AT_FIRST_TRADABLE_PRICE = "FILLED_AT_FIRST_TRADABLE_PRICE"
    SUSPENDED = "SUSPENDED"
    UNSAFE_DATA = "UNSAFE_DATA"


class FillModel(StrEnum):
    FULL_FILL = "full_fill"
    VOLUME_LIMITED = "volume_limited"
    CONSERVATIVE_VOLUME_LIMITED = "conservative_volume_limited"


class TradingState(StrEnum):
    OPENING_AUCTION = "OPENING_AUCTION"
    CONTINUOUS = "CONTINUOUS"
    CLOSING_AUCTION = "CLOSING_AUCTION"
    ORDER_COLLECTION = "ORDER_COLLECTION"
    SINGLE_PRICE = "SINGLE_PRICE"
    CIRCUIT_BREAKER = "CIRCUIT_BREAKER"
    SUSPENDED = "SUSPENDED"
    CLOSED = "CLOSED"
    NO_VALID_TRADE = "NO_VALID_TRADE"


class PricePurpose(StrEnum):
    BUY_LIMIT = "BUY_LIMIT"
    ENTRY_ZONE_LOW = "ENTRY_ZONE_LOW"
    ENTRY_ZONE_HIGH = "ENTRY_ZONE_HIGH"
    BREAKOUT_TRIGGER = "BREAKOUT_TRIGGER"
    PROTECTIVE_STOP_LONG = "PROTECTIVE_STOP_LONG"
    TARGET_LONG = "TARGET_LONG"
    MANUAL_EXIT = "MANUAL_EXIT"
    REFERENCE_PRICE = "REFERENCE_PRICE"


class RoundingDirection(StrEnum):
    FLOOR = "FLOOR"
    CEILING = "CEILING"
    NEAREST = "NEAREST"


class ExitOrderType(StrEnum):
    TARGET = "TARGET"
    STOP = "STOP"
    MANUAL = "MANUAL"


class TargetStatus(StrEnum):
    PENDING = "PENDING"
    EXECUTED = "EXECUTED"


class StopPolicy(StrEnum):
    FIXED_STOP = "FIXED_STOP"
    BREAKEVEN_AFTER_TP1 = "BREAKEVEN_AFTER_TP1"
    TP1_STOP_AFTER_TP2 = "TP1_STOP_AFTER_TP2"
    ATR_TRAILING = "ATR_TRAILING"
    STRUCTURE_TRAILING = "STRUCTURE_TRAILING"
    MANUAL_TRAILING = "MANUAL_TRAILING"
